import { useState } from "react";
import Head from "next/head";
import { Field, Form, Formik, useFormik } from "formik";
import {
  Box,
  Button,
  CircularProgress,
  CssBaseline,
  FormControl,
  FormHelperText,
  IconButton,
  InputAdornment,
  InputLabel,
  OutlinedInput,
  TextField,
  Typography,
} from "@mui/material";
import { Check, Visibility, VisibilityOff } from "@mui/icons-material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <main></main>
    </>
  );
}
